import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const daxlight = localFont({
  src: "./fonts/dax-light.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const daxbold = localFont({
  src: "./fonts/dax-bold.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Authentification prestataire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${daxlight.variable} ${daxbold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
